### ISSUE TITLE
Track whale portfolios across markets

### ISSUE THREAD

**Issue by larry77** [TrevorFrench/cryptotrackr#43]
Hello, not really a bug, but a question. Cryptotrackr is described as able to track portfolios, but how to achieve that? In particular I would like to track big buyers across different crypto exchanges. Thanks!

**Comment by TrevorFrench** [comment]
Hi Larry-

Unfortunately, I am not aware of a way you would be able to track other people's portfolios across centralized exchanges. However, if you feel there are API methods that should be incorporated into this package which would help you to achieve your goals, I would be happy to add them.

You are able to view order books on most exchanges though. The following example demonstrates how you could retrieve the bids and asks from blockchain.com.

```
symbol <- 'BTC-USD'
l2_order_book <- blockchain_dot_com_l2_order_book(symbol)
bids <- l2_order_book$bids
asks <- l2_order_book$asks
```

If you wanted to look at executed trades instead of order books, most exchanges will have methods for that as well. This example demonstrates how you could retrieve recently executed trades for the "LTCBTC" pair on Binance.us.

```
symbol <- 'LTCBTC'
limit <- '1000'
recent_trades <- binance_us_recent_trades(symbol, limit)
```

Alternatively, if you wanted to track portfolios for on-chain activity you could use the following example to retrieve portfolio balance as well as transaction history for any specified address through the Covalent API.

```
api_key <- "..."
balances <- covalent_balances(api_key, "1", "trevorfrench.eth", csv = FALSE)
portfolio_history <- covalent_portfolio(api_key, "1", "trevorfrench.eth", csv = FALSE)
```

**Comment by larry77** [comment]
I see. It would still be useful to add some functions to make the output of the portfolio_history object more readable.
Long story short: have a look at

https://etherscan.io/token/0x62d0a8458ed7719fdaf978fe5929c6d342b0bfce?a=0x6bdabb7c6ac53552224d5b8a1d57b9d83c41cb03

This is an entity which sold a lot of beam coins bringing forth its significant dip at the moment when I write this.

In the reprex below, I follow your advice and then I try to rectangle (see https://cran.r-project.org/web/packages/unnest/vignettes/tidyr.html) the output, but I am not so sure it is the right approach since it may not be very easy to figure out what is going on by looking at portfolio_history_rectangled. Do you have any other/better ideas?

Thanks!

``` r
library(tidyverse)
library(janitor)
#> 
#> Attaching package: 'janitor'
#> The following objects are masked from 'package:stats':
#> 
#>     chisq.test, fisher.test
library(cryptotrackr)

library(unnest)
#> 
#> Attaching package: 'unnest'
#> The following object is masked from 'package:readr':
#> 
#>     spec
#> The following object is masked from 'package:tidyr':
#> 
#>     unnest
options(unnest.return.type = "tibble")

## Use  covalent api to extract the transaction data you find at

## See https://etherscan.io/token/0x62d0a8458ed7719fdaf978fe5929c6d342b0bfce?a=0x6bdabb7c6ac53552224d5b8a1d57b9d83c41cb03


api_key <- "..."

address <- "0x6bdabB7c6ac53552224d5B8a1d57B9d83c41cB03"

chain_id <- "1" ## etherscan

portfolio_history <- covalent_portfolio(api_key, chain_id,
                            address, csv = FALSE) 


portfolio_history_rectangled <- portfolio_history |>
    unnest() |>
    clean_names()

portfolio_history_rectangled |>
    glimpse()
#> Rows: 31
#> Columns: 41
#> $ data_address                             <chr> "0x6bdabb7c6ac53552224d5b8a1d…
#> $ data_chain_id                            <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
#> $ data_chain_name                          <chr> "eth-mainnet", "eth-mainnet",…
#> $ data_items_contract_address              <chr> "0x62d0a8458ed7719fdaf978fe59…
#> $ data_items_contract_decimals             <int> 18, 18, 18, 18, 18, 18, 18, 1…
#> $ data_items_contract_name                 <chr> "Beam", "Ether", "Beam", "Eth…
#> $ data_items_contract_ticker_symbol        <chr> "BEAM", "ETH", "BEAM", "ETH",…
#> $ data_items_holdings_1_close_balance      <chr> "257952587831662109841738532"…
#> $ data_items_holdings_1_close_pretty_quote <chr> "$5,111,915.00", "$4,817,604.…
#> $ data_items_holdings_1_close_quote        <dbl> 5111915, 4817604, 5414250, 98…
#> $ data_items_holdings_1_high_balance       <chr> "257952587831662109841738532"…
#> $ data_items_holdings_1_high_pretty_quote  <chr> "$5,111,915.00", "$4,891,727.…
#> $ data_items_holdings_1_high_quote         <dbl> 5111915, 4891727, 8514941, 98…
#> $ data_items_holdings_1_low_balance        <chr> "257952587831662109841738532"…
#> $ data_items_holdings_1_low_pretty_quote   <chr> "$5,111,915.00", "$3,024,095.…
#> $ data_items_holdings_1_low_quote          <dbl> 5111915, 3024096, 5414250, 0,…
#> $ data_items_holdings_1_open_balance       <chr> "257952587831662109841738532"…
#> $ data_items_holdings_1_open_pretty_quote  <chr> "$5,111,915.00", "$4,891,727.…
#> $ data_items_holdings_1_open_quote         <dbl> 5111915, 4891727, 8514941, 0,…
#> $ data_items_holdings_1_quote_rate         <dbl> 0.019817265, 0.018676316, 0.0…
#> $ data_items_holdings_1_timestamp          <chr> "2023-12-17T20:43:19.99937562…
#> $ data_items_holdings_2_close_balance      <chr> "390556585743409048", "390556…
#> $ data_items_holdings_2_close_pretty_quote <chr> "$875.36", "$869.96", "$865.8…
#> $ data_items_holdings_2_close_quote        <dbl> 875.3594, 869.9593, 865.8656,…
#> $ data_items_holdings_2_high_balance       <chr> "390556585743409048", "390556…
#> $ data_items_holdings_2_high_pretty_quote  <chr> "$875.36", "$869.96", "$865.8…
#> $ data_items_holdings_2_high_quote         <dbl> 875.3594, 869.9593, 865.8656,…
#> $ data_items_holdings_2_low_balance        <chr> "390556585743409048", "390556…
#> $ data_items_holdings_2_low_pretty_quote   <chr> "$875.36", "$869.96", "$865.8…
#> $ data_items_holdings_2_low_quote          <dbl> 875.3594, 869.9593, 865.8656,…
#> $ data_items_holdings_2_open_balance       <chr> "390556585743409048", "390556…
#> $ data_items_holdings_2_open_pretty_quote  <chr> "$875.36", "$869.96", "$865.8…
#> $ data_items_holdings_2_open_quote         <dbl> 875.3594, 869.9593, 865.8656,…
#> $ data_items_holdings_2_quote_rate         <dbl> 2241.312, 2227.486, 2217.004,…
#> $ data_items_holdings_2_timestamp          <chr> "2023-12-17T20:43:19.99937562…
#> $ data_items_logo_url                      <chr> "https://logos.covalenthq.com…
#> $ data_items_supports_erc                  <lgl> NA, NA, NA, NA, NA, NA, NA, N…
#> $ data_next_update_at                      <chr> "2023-12-17T20:48:20.57946799…
#> $ data_quote_currency                      <chr> "USD", "USD", "USD", "USD", "…
#> $ data_updated_at                          <chr> "2023-12-17T20:43:20.57946755…
#> $ error                                    <lgl> FALSE, FALSE, FALSE, FALSE, F…


## is there a more expressive way to handle this?
```

<sup>Created on 2023-12-17 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by TrevorFrench** [comment]
@larry77 If I'm understanding you correctly, I think you would be better served by changing the "csv" parameter to "TRUE" as demonstrated in the following example. This will return a dataframe with 20 columns with each record seeming to represent the daily portfolio information for a single asset.

```
portfolio_history_csv <- covalent_portfolio(api_key, chain_id,
                                            address, csv = TRUE)
```

I hope that's useful for you. In any case you do bring up a good point- a lot of the other methods in the package currently return nested lists which may not be the easiest to interact with in R. I will put some thought into how to make them more user-friendly going forward.

Meanwhile, I think your reprex is an excellent example of how users can get by until alternatives are available.

**Comment by larry77** [comment]
OK, let us close this issue (which was rather a question). My two final remarks
1) there should be an option in the api call to covalent about how many days of transactions to retrieve.
2) whichever way I look at it, I find the output of querying a portfolio history rather confusing. It is not clear even what comes in and out of a portfolio and, apart from the value in USD, how many coins are involved in each transaction (but I do not know if this is a limitation of the free API).

Keep up the good work!
