### ISSUE TITLE
Solana examples failing

### ISSUE THREAD

**Issue by TrevorFrench** [TrevorFrench/cryptotrackr#54]
The Solana examples started to fail resulting on the package being removed from CRAN.

**Comment by TrevorFrench** [comment]
It looks like the tests and examples are just being rate limited: https://cran-archive.r-project.org/web/checks/2024/2024-03-31_check_results_cryptotrackr.html

**Comment by serkor1** [comment]
I was wondering why all your downloads suddenly flatlined like Luna! 😊

**Comment by TrevorFrench** [comment]
Lol I deployed a fix but still waiting for it to be approved 🥲

**Comment by serkor1** [comment]
> Lol I deployed a fix but still waiting for it to be approved 🥲

Could be they are treating it as new submission if they already removed the package.

When I resubmit its usually live with a couple of hours!
